# Generated by Django 5.2.4 on 2025-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorINE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
            options={
                'unique_together': {('codigo', 'año', 'mes')},
            },
        ),
    ]
